### ISSUE TITLE
Runtime failure: "no valid keystore"

### ISSUE THREAD

**Issue by brampersandon** [Unicon/shibboleth-idp-dockerized#23]
Hi, all! First off, thanks so much for setting up a dockerized version of the IdP -- it's hugely helpful for those of us exploring a more composable identity management structure.

As I've been working with the image, it seems as though the generated configuration files (which come from `docker run -it -v $(pwd):/ext-mount --rm unicon/shibboleth-idp init-idp.sh`) create an invalid keystore file at `/customized-shibboleth-idp/credentials/sealer.jks`. 

When I run the app with my keystore passwords in the following environment variables:

```
JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=Not_really_my_password
JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=Not_really_my_password
```

and a Dockerfile that copies the /shibboleth-idp/ directory as described in the README: 
`ADD shibboleth-idp/ /opt/shibboleth-idp/`

I can launch the daemon as specified in the README with `docker run -d -p 443:4443 --name <container-name> <image-name>`, but when hitting <docker-host-ip>:443/idp, nothing happens.

Investigating this with `docker logs`, I find the following error: 

```
Exception in thread "main" java.lang.IllegalStateException: no valid keystore
    at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:48)
    at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1016)
    at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:332)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:64)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:260)
    at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
    at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.server.Server.doStart(Server.java:384)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1510)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435)
```

Checking the keystore file with `keytool` indicates the keystore file may be invalid:

```
# ~/shibboleth-idp/credentials# keytool -list -keystore sealer.jks
keytool error: java.io.IOException: Invalid keystore format
```

Please let me know if there's any additional info I can provide. Thanks again!

**Comment by jtgasper3** [comment]
@skylineproject,

Glad this project has been helpful to you... 

So a quick note on secrets used in this container/shib in general.

You mentioned:

```
JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=Not_really_my_password
JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=Not_really_my_password
```

The Backchannel key is one that is passed in via the shib install. The **Browser** password has nothing to do with the **Sealer** password which was also used in the install. The sealer is used to encrypt cookies sent by the idp to a browser.

The **Browser** key store is used by an TLS/SSL cert that you create manually. This is the key/cert that is used when the browser connects to the web server (load balancer, jetty, etc). If the browser is connecting directly to Jetty, then you'd want to get this cert signed by a trusted CA like Verisign, Commodo, DigiCert, etc.

If you terminate browser-side SSL on something but Jetty, then a self signed cert will work. I created one yesterday:

```
openssl req -new -x509 -newkey rsa:2048 -sha256 -key jetty.key -out jetty.crt
openssl pkcs12 -inkey jetty.key -in jetty.crt -export -out idp-browser.p12
```

> The readme has a link to the Jetty docs that explain how to use openssl to do this for a CA signed cert. 

The `idp-browser.p12` generated by the above needs to be dropped in the credentials directory.

The Browser and Backchannel files are pkcs12 formats and not the standard JKS files.

As for using keytool to browser the sealer.jks file. I'll have to look into that, but it is used internally by the IdP code base and not by Jetty.

Let me know if that helps you out.

**Comment by brampersandon** [comment]
Thanks so much for your reply! I had a feeling I was conflating something here that wasn't quite right -- this clarification is hugely helpful. As you might imagine, I'm only running this (experimentally) on my local Docker host, so I'm going to go the self-signed route at the moment. Generating a cert resolves the error I was seeing, so I do think we're in good shape on that front. Thanks again!

**Comment by jtgasper3** [comment]
Glad to hear. You are very welcome.

**Comment by ozbillwang** [comment]
@jtgasper3 

I followed all steps include the extra step to generate `idp-browser.p12` ( I used the free letsencrypt certificate keys) and copy it to `credentials` folder

```
$ openssl pkcs12 -inkey privkey1.pem -in cert1.pem -certfile chain1.pem -export -out idp-browser.p12
Enter Export Password:
Verifying - Enter Export Password:
```

Seems this new generated key `idp-browser.p12`  fixs the `no valid keystore` issue, thanks.

```
2016-07-29 07:09:32.518:INFO:oejs.ServerConnector:main: Started ServerConnector@6ec63f8{SSL,[ssl, http/1.1]}{0.0.0.0:4443}
2016-07-29 07:09:32.518:INFO:oejs.Server:main: Started @34862ms
```

**Comment by Loki-Afro** [comment]
@jtgasper3 didng't you mean `keyout` instead of `key` here?

`openssl req -new -x509 -newkey rsa:2048 -sha256 -key jetty.key -out jetty.crt`

**Comment by jtgasper3** [comment]
@Loki-Afro, I guess I need more context... At the end of the day, one just needs a .p12 file. 

In the readme, I reference https://www.eclipse.org/jetty/documentation/current/configuring-ssl.html (see Generating Keys and Certificates with OpenSSL) and don't actually suggest how to make the .p12 file step-by-step. The commands I posted earlier in this thread came from that doc.

**Comment by Sarek-Wyona** [comment]
I know this issue has been closed, but I am still running into this. I am running this container locally. my run command looks as follows: 

```
docker run -p 443:4443 -p 8443:8443 -d --name="shib-local-test" cs/shibboleth-idp:3.3.2
```

I generated new certs with the following commands: 

```
openssl genrsa -out idp.key 2048
openssl req -new -x509 -nodes -sha1 -days 7305 -key idp.key -out idp.crt
openssl pkcs12 -export -in idp.crt -inkey idp.key -out idp-browser.p12
```

and have the idp-browser.p12 in my credentials folder. But when I try to hit the following IP I get nothing. 

```
https://localhost/idp/
```

The error I see is as follows: 

```
2017-12-01 07:48:16.563:INFO:oejs.AbstractConnector:main: Started ServerConnector@57352243{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
2017-12-01 07:48:16.564:INFO:oejs.AbstractConnector:main: Started ServerConnector@4b87760e{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
Exception in thread "main" java.lang.IllegalStateException: no valid keystore
	at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:48)
	at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1037)
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:254)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:221)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:72)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:268)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1540)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1462)
```

Any help will be appreciated.
