### ISSUE TITLE
java.io.IOException: keystore password was incorrect

### ISSUE THREAD

**Issue by mim-Armand** [Unicon/shibboleth-idp-dockerized#48]
Hi,
Trying to run this image, following the guidelines provided, I get the following error:
```java
java.io.IOException: keystore password was incorrect
```

The stack trace look like:

```java
Exception in thread "main" MultiException[java.io.IOException: keystore password was incorrect, java.io.IOException: keystore password was incorrect]
	at org.eclipse.jetty.server.Server.doStart(Server.java:386)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1540)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1462)
	Suppressed: java.io.IOException: keystore password was incorrect
		at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2015)
		at java.security.KeyStore.load(KeyStore.java:1445)
		at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:52)
		at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1037)
		at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:254)
		at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:221)
		at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
		at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
		at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
		at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:72)
		at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
		at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
		at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
		at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:268)
		at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
		at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
		at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
		at org.eclipse.jetty.server.Server.doStart(Server.java:401)
		... 4 more
	Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded
		... 22 more
Caused by: java.io.IOException: keystore password was incorrect
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2015)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:52)
	at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1037)
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:254)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:221)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:72)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:268)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
	... 4 more
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded
	... 22 more
```
I have provided a valid p12 cert and put it in the `shiboleth-idp/credentials`.
I also tried to creat the **P12** file with and without password and providing the same password when running the setup script (it doesn't accept an empty string tho, so I had to enter a password there eitherway)

Any idea what could be the problem or if you can confirm that the container works for you?
Thanks

**Comment by mim-Armand** [comment]
I found that this was answered near the end of the documentation after founding how to solve it the hard way!
The solution was to either using the default `changeme` password for cacerts or provide the env-var with the new password when running it ( as mentioned in the env vars in the `readme.md` file )
