### ISSUE TITLE
Status page?

### ISSUE THREAD

**Issue by CsatariGergely** [Unicon/shibboleth-idp-dockerized#55]
This is a question and not an issue. 
I built and started the customized container successfully, but I do not know how to check if the IdP runs okay. It looks like the status page is disabled and when I tried to allow it based on point 4 [here](https://github.com/malavolti/HOWTO-Install-and-Configure-Shibboleth-Identity-Provider/blob/master/HOWTO%20Install%20and%20Configure%20a%20Shibboleth%20v3.2.1%20on%20Ubuntu%20Linux%20LTS%2014.04%20with%20Tomcat%208%20only.md#install-shibboleth-identity-provider-v321) I got an exception.
Any idea what do I do wrong?
Thanks.

**Comment by jtgasper3** [comment]
Can you please include info about the exception, like the full stacktrace and a few lines before and after it?

**Comment by CsatariGergely** [comment]
I think this is the most interesting part: 
2018-08-08 09:27:10,927 - ERROR [org.springframework.web.context.ContextLoader:350] - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.ReloadableAccessControlService' defined in file [/opt/shibboleth-idp/system/conf/services-system.xml]: Invocation of init method failed; nested exception is net.shibboleth.utilities.java.support.component.ComponentInitializationException: Service 'shibboleth.ReloadableAccessControlService': could not perform initial load
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
Caused by: net.shibboleth.utilities.java.support.component.ComponentInitializationException: Service 'shibboleth.ReloadableAccessControlService': could not perform initial load
	at net.shibboleth.utilities.java.support.service.AbstractReloadableService.doInitialize(AbstractReloadableService.java:179)
Caused by: net.shibboleth.utilities.java.support.service.ServiceException: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 1 in XML document from file [/opt/shibboleth-idp/conf/access-control.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 49; The prefix "util" for element "util:map" is not bound.
	at net.shibboleth.ext.spring.service.ReloadableSpringService.doReload(ReloadableSpringService.java:336)
Caused by: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 1 in XML document from file [/opt/shibboleth-idp/conf/access-control.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 49; The prefix "util" for element "util:map" is not bound.
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:399)
Caused by: org.xml.sax.SAXParseException: The prefix "util" for element "util:map" is not bound.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)


And the related configuration in /shibboleth-idp-dockerized-custom/shibboleth-idp/conf/access-control.xml:
<util:map id="shibboleth.AccessControlPolicies">
  <entry key="AccessByIPAddress">
    <bean parent="shibboleth.IPRangeAccessControl" p:allowedRanges="#{ {'127.0.0.1/32', '::1/128', '127.0.0.1/24'} }" />
  </entry>
</util:map>

My current target is get something positive back form /opt/shibboleth-idp/bin/status.sh .

Thanks.

**Comment by jtgasper3** [comment]
@CsatariGergely Sorry, I never circled back around to this. This is an issue with your IdP configuration itself and not the Docker image.

**Comment by CsatariGergely** [comment]
@jtgasper3 Yes, it is something around my IdP config.
