### ISSUE TITLE
Jetty repo broken

### ISSUE THREAD

**Issue by ghost** [Unicon/shibboleth-idp-dockerized#71]
It seems like the jetty repo URL is broken.

DOWNLOAD: https://raw.githubusercontent.com/eclipse/jetty.project/master/jetty-server/src/test/config/etc/keystore?id=master to ${jetty.base}/etc/keystore
java.io.IOException: URL GET Failure [404/Not Found] on https://raw.githubusercontent.com/eclipse/jetty.project/master/jetty-server/src/test/config/etc/keystore?id=master
        at org.eclipse.jetty.start.fileinits.UriFileInitializer.download(UriFileInitializer.java:79)
        at org.eclipse.jetty.start.fileinits.UriFileInitializer.init(UriFileInitializer.java:60)
        at org.eclipse.jetty.start.BaseBuilder.processFileResource(BaseBuilder.java:283)
        at org.eclipse.jetty.start.BaseBuilder.processFileResources(BaseBuilder.java:375)
        at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:239)
        at org.eclipse.jetty.start.Main.start(Main.java:406)
        at org.eclipse.jetty.start.Main.main(Main.java:76)
MKDIR: ${jetty.base}/webapps

**Comment by lrhazi** [comment]
FYI. see my comment here:  https://github.com/Unicon/shibboleth-idp-dockerized/issues/73#issuecomment-641389666

**Comment by winstonhong** [comment]
@lucasmellos We just fixed the two (2) issues related to Jetty repo broken for Shibboleth IdP and SP based on Unicon's Shibboleth IdP and SP Docker image which have been cited in README. 

I have validated all the the three (3) projects with the latest commit (i.e., commit 21) based on README tutorial on brand-new Ubuntu 18.04. 

https://github.com/winstonhong/Shibboleth-SAML-IdP-and-SP
